sonar.projectKey=devopswithprashant_dwp-platform-ui_e76128a0-11d6-4ca7-853f-9fbf7c7b800d
sonar.projectName=dwp-platform-ui

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/__tests__/**/*.test.ts,src/**/__tests__/**/*.test.tsx

# Path to LCOV coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Path to Jest test execution report
sonar.testExecutionReportPaths=coverage/test-report.xml

# Exclude tests and config files from coverage calculation
sonar.coverage.exclusions=src/**/__tests__/**,**/*.config.js,**/*.config.ts
