sonar.projectKey=devopswithprashant_dwp-platform-ui_e76128a0-11d6-4ca7-853f-9fbf7c7b800d
sonar.projectName=dwp-platform-ui

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src

sonar.test.inclusions=src/**/__tests__/**/*.test.ts,src/**/__tests__/**/*.test.tsx

# Path to the generated LCOV coverage file
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=coverage/test-report.xml

# Exclude test files, configuration files, and type definitions from coverage metrics

sonar.coverage.exclusions=\
  src/**/*.d.ts,\
  src/**/types.ts,\
  src/proxy.ts,\
  src/app/layout.tsx,\
  src/app/api/**/*,\
  src/**/__tests__/**/*,\
  src/**/*.test.ts,\
  src/**/*.test.tsx

