apiVersion: v1
kind: Service
metadata:
  name: dwp-platform-ui
  namespace: dwp-platform
  labels:
    app: dwp-platform-ui
    app.kubernetes.io/name: dwp-platform-ui
spec:
  type: ClusterIP
  selector:
    app: dwp-platform-ui
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: nextjs-metrics
      port: 3000
      targetPort: nextjs-metrics
    - name: nginx-metrics
      port: 9113
      targetPort: nginx-metrics
