import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeToggle from "./_components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <header className="sticky top-0 z-30 border-b border-gray-200/60 bg-background/80 backdrop-blur dark:border-gray-800/80">
          <nav className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
            <Link
              href="/"
              className="text-sm font-semibold tracking-tight text-gray-500 transition hover:text-foreground"
            >
              DevOps With Prashant
            </Link>
            <div className="flex flex-1 items-center justify-center gap-1 text-sm font-medium">
              <Link
                href="/"
                className="rounded-full px-3 py-1.5 text-gray-700 transition hover:bg-gray-100 hover:text-gray-900 dark:text-gray-200 dark:hover:bg-gray-900"
              >
                Home
              </Link>
              <Link
                href="/blogs"
                className="rounded-full px-3 py-1.5 text-gray-700 transition hover:bg-gray-100 hover:text-gray-900 dark:text-gray-200 dark:hover:bg-gray-900"
              >
                Blog
              </Link>
            </div>
            <div className="flex items-center justify-end gap-3">
              <ThemeToggle />
            </div>
          </nav>
        </header>
        <main className="min-h-screen bg-gradient-to-b from-background to-gray-50/60 text-foreground dark:from-background dark:to-black">
          {children}
        </main>
      </body>
    </html>
  );
}
