# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: PR build check

on:
  pull_request_target: # Loads this workflow file from the base branch (e.g. main)
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write 



concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false



env:
  ARTIFACTORY_DEV_USER: ${{ secrets.ARTIFACTORY_DEV_USER }}
  ARTIFACTORY_DEV_KEY: ${{ secrets.ARTIFACTORY_DEV_KEY }}
  ARTIFACTORY_RELEASE_USER: ${{ secrets.ARTIFACTORY_RELEASE_USER }}
  ARTIFACTORY_RELEASE_KEY: ${{ secrets.ARTIFACTORY_RELEASE_KEY }}
  # Set defaults here or as repository/organization variables (recommended)
  AWS_REGION: us-east-1           # <- change to your region or set as repo variable
  AWS_ACCOUNT_ID: 850756192530      # <- change to your AWS account id or set as repo var
  ECR_REPOSITORY: dwp/np/ui            # <- change to your ECR repository name
  GIT_USER_NAME: "ci-bot"
  GIT_USER_EMAIL: "ci-bot@devopswithprashant.com"




jobs:
  maven:
    runs-on: ubuntu-latest
    outputs:
      projectVersion: ${{ steps.project_version.outputs.version }}
    steps:

    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.11

    
    - name: Get project version from POM
      id: project_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    # - name: Lint
    #   run: |
    #     mvn validate generate-resources verify
    #     mvn frontend:npm -Darguments="run lint"

    # - name: Build
    #   run: |
    #     mvn clean package --file pom.xml -DskipTests -B
  
    # - name: Test
    #   run: mvn clean test 

    - name: Clean and Install Dependencies
      run: |
        mvn clean validate generate-resources --file pom.xml -B
    
    - name: Run Linting
      run: |
        mvn verify -DskipTests --file pom.xml -B
    
    - name: Run Tests
      run: |
        mvn test --file pom.xml -B -Dorg.slf4j.simpleLogger.defaultLogLevel=info

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v8.1.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectVersion=${{ steps.project_version.outputs.version }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    

    - name: Build and push to ECR
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        platforms: linux/arm64
        tags: |
          dwp-ui:${{ github.sha }}
        # Optional: use GitHub Actions cache for build layers (fast incremental builds)
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: 'dwp-ui:${{ github.sha }}'
        format: 'table'
        exit-code: '1'          # Fails the pipeline if vulnerabilities are found
        ignore-unfixed: true     # Optional: ignore CVEs without an available fix
        severity: 'CRITICAL,HIGH'

